name: notes
description: My Notes App.,

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_automation: ^1.4.0
  sqflite: ^2.0.0+2
  path_provider: ^2.0.1
  provider: ^5.0.0
  image_picker: ^0.6.7+14
  google_fonts: ^1.1.0
  intl: ^0.16.1
  url_launcher: ^6.0.2
  permission_handler: ^5.0.1+1
  matrix4_transform: ^2.0.0
  fluttertoast: ^7.1.5
  local_auth: ^0.6.3+4
  shared_preferences: ^2.0.3
  flutter_tabler_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^0.1.2



  pedantic: ^1.9.2
  effective_dart: ^1.3.0
  test: ^1.15.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/test.png